export const HANDLER_GET_TOPIC = 'get_topic'
export const HANDLER_RECENT_TOPICS = 'recent_topics'
export const HANDLER_ALL_TOPICS = 'all_topics'
export const HANDLER_RECENT_POSTS = 'recent_posts'
export const HANDLER_ALL_POSTS = 'all_posts'